// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKDGhlE2yJDR3ZYg22TbtT1YNy7HXR1Vo',
    appId: '1:507963375980:web:5c948fd764f37aa43ef349',
    messagingSenderId: '507963375980',
    projectId: 'scanall1',
    authDomain: 'scanall1.firebaseapp.com',
    storageBucket: 'scanall1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCip2chfjncyx0i3fiVfsK4bQf5y-s7Gsw',
    appId: '1:507963375980:android:ed001eea51518b013ef349',
    messagingSenderId: '507963375980',
    projectId: 'scanall1',
    storageBucket: 'scanall1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAnTTZbxh3ua3jPEUVBbzPPvLhSbR6Pwk',
    appId: '1:507963375980:ios:c9a66bfc6e8f3a623ef349',
    messagingSenderId: '507963375980',
    projectId: 'scanall1',
    storageBucket: 'scanall1.firebasestorage.app',
    iosBundleId: 'com.example.mytask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAnTTZbxh3ua3jPEUVBbzPPvLhSbR6Pwk',
    appId: '1:507963375980:ios:c9a66bfc6e8f3a623ef349',
    messagingSenderId: '507963375980',
    projectId: 'scanall1',
    storageBucket: 'scanall1.firebasestorage.app',
    iosBundleId: 'com.example.mytask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKDGhlE2yJDR3ZYg22TbtT1YNy7HXR1Vo',
    appId: '1:507963375980:web:22448210398708983ef349',
    messagingSenderId: '507963375980',
    projectId: 'scanall1',
    authDomain: 'scanall1.firebaseapp.com',
    storageBucket: 'scanall1.firebasestorage.app',
  );
}
